 CREATE TABLE `cd_order_250811` (
  `order_id` int NOT NULL AUTO_INCREMENT,
  `orderid` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `merchantid` int DEFAULT NULL COMMENT '商户ID',
  `sysorderid` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '系统订单号',
  `amount` decimal(20,4) DEFAULT NULL COMMENT '金额',
  `status` smallint DEFAULT '2' COMMENT '状态',
  `remarks` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '备注',
  `create_time` int DEFAULT NULL COMMENT '创建时间',
  `update_time` int DEFAULT NULL COMMENT '更新时间',
  `completetime` int DEFAULT NULL COMMENT '完成时间',
  `proxy_id` smallint DEFAULT NULL COMMENT '卡商',
  `merchantnumber` smallint DEFAULT NULL COMMENT '类型',
  `username` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '会员姓名',
  `date` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '订单创建时间',
  `callbackurl` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '跳转地址',
  `notifyurl` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '异步通知地址',
  `account` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '收款账号',
  `realname` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '收款人名称',
  `bank` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '银行名称',
  `bankname` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '开户行',
  `service_id` smallint DEFAULT NULL COMMENT '客服',
  `notify_status` tinyint unsigned NOT NULL DEFAULT '0',
  `notify_num` smallint unsigned NOT NULL DEFAULT '0',
  `pay_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '付款人',
  `kh_ip` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '客户IP',
  `kouling` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '0' COMMENT '口令',
  `other_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '三方订单状态:0=处理中,1=成功',
  `other_json` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `qr_code` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `sf_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `num` smallint unsigned DEFAULT '0',
  `inizt` int NOT NULL DEFAULT '0',
  `sdzt` int DEFAULT '0',
  `yh_bq` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `time` decimal(20,1) DEFAULT NULL,
  `sf_xr` int DEFAULT NULL,
  `bank_lx` int DEFAULT '0',
  `amount_real` decimal(20,4) DEFAULT NULL,
  `bank_open` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '收付款方式1：银行卡2AnSpace',
  `amount_real_pay` decimal(20,4) NOT NULL DEFAULT '0.0000' COMMENT '实际付款金额',
  `pay_time` int DEFAULT '0' COMMENT '付款时间(银行到账时间)',
  `df_fee` decimal(20,4) NOT NULL DEFAULT '0.0000' COMMENT '代付手续费',
  `agent_commission` decimal(20,4) NOT NULL DEFAULT '0.0000' COMMENT '代理佣金',
  PRIMARY KEY (`order_id`),
  KEY `orderid` (`orderid`) USING BTREE,
  KEY `cd_order_merchantid_merchantnumber_create_time_index` (`merchantid`,`merchantnumber`,`create_time`,`status`) USING BTREE,
  KEY `cd_order_inizt_index` (`inizt`) USING BTREE,
  KEY `status` (`status`,`create_time`,`notify_status`,`notify_num`,`sdzt`) USING BTREE,
  KEY `notify_status` (`notify_status`,`notify_num`,`sdzt`) USING BTREE,
  KEY `completetime` (`completetime`) USING BTREE,
  KEY `bank_open` (`bank_open`) USING BTREE,
  KEY `bank_lx` (`bank_lx`) USING BTREE,
  KEY `createtime_completetime` (`create_time`,`completetime`) USING BTREE,
  KEY `yh_bq` (`yh_bq`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3;





 CREATE TABLE `cd_moneylog_250811` (
  `moneylog_id` int NOT NULL AUTO_INCREMENT,
  `service_id` int DEFAULT NULL COMMENT '客服',
  `proxy_id` int DEFAULT NULL COMMENT '码商',
  `merchant_id` int DEFAULT NULL COMMENT '商户',
  `type` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '变动类型',
  `action` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '方法',
  `begin` decimal(20,3) DEFAULT '0.000' COMMENT '期初金额',
  `after` decimal(20,3) DEFAULT '0.000' COMMENT '期末金额',
  `money` decimal(20,3) DEFAULT '0.000' COMMENT '发生额',
  `content` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '详情',
  `remark` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '备注',
  `ext` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci COMMENT '扩展内容',
  `adduser` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '操作人',
  `create_time` int DEFAULT NULL COMMENT '创建时间',
  `test` int NOT NULL DEFAULT '0',
  `sxf` decimal(3,3) DEFAULT '0.000',
  `bank_lx` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '收付款方式1：银行卡2AnSpace',
  PRIMARY KEY (`moneylog_id`),
  UNIQUE KEY `proxy_id` (`proxy_id`,`merchant_id`,`money`,`create_time`) USING BTREE,
  KEY `cd_moneylog_create_time_type_index` (`create_time`,`type`) USING BTREE,
  KEY `cd_moneylog_merchant_id_type_index` (`merchant_id`,`type`) USING BTREE,
  KEY `bank_lx` (`bank_lx`) USING BTREE,
  KEY `adduser` (`adduser`) USING BTREE,
  KEY `action` (`action`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3;





